/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.senai.sp.jandira.ui;

import br.senai.sp.jandira.model.TipoOperacao;

/**
 *
 * @author 22282085
 */
public class MedicoDialog extends javax.swing.JFrame {

    /**
     * Creates new form MedicoDialog
     */
    public MedicoDialog() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        labelmedico = new javax.swing.JLabel();
        labelicone = new javax.swing.JLabel();
        labeltitulo = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        labelcodigo = new javax.swing.JLabel();
        labelsubtitulo = new javax.swing.JLabel();
        textcodigo = new javax.swing.JTextField();
        labeloperadora = new javax.swing.JLabel();
        textoperadora = new javax.swing.JTextField();
        labelplano = new javax.swing.JLabel();
        textplano = new javax.swing.JTextField();
        buttonsalvar = new javax.swing.JButton();
        buttoncancelar = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        labelcrm = new javax.swing.JLabel();
        labelsubtitulo1 = new javax.swing.JLabel();
        textcrm = new javax.swing.JTextField();
        labeltelefone = new javax.swing.JLabel();
        texttelefone = new javax.swing.JTextField();
        labeldata = new javax.swing.JLabel();
        textdata = new javax.swing.JTextField();
        buttonsalvar1 = new javax.swing.JButton();
        buttoncancelar1 = new javax.swing.JButton();
        labelespecialidade = new javax.swing.JLabel();
        labelcodigo3 = new javax.swing.JLabel();
        textnomemedico = new javax.swing.JTextField();
        textcodigo3 = new javax.swing.JTextField();
        labelemail = new javax.swing.JLabel();
        textemail = new javax.swing.JTextField();
        labelespmedico = new javax.swing.JLabel();
        labelnomemedico = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlistespmedico = new javax.swing.JList<>();
        jlistespecialidade = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jbuttondireita = new javax.swing.JButton();
        jbuttonesquerda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.setLayout(null);

        labelmedico.setBackground(new java.awt.Color(255, 255, 255));
        labelmedico.setFont(new java.awt.Font("Segoe Script", 0, 24)); // NOI18N
        labelmedico.setText("Médico");
        jPanel3.add(labelmedico);
        labelmedico.setBounds(10, 0, 260, 39);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 0, 830, 30);

        labelicone.setForeground(new java.awt.Color(255, 255, 255));
        labelicone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/menu.icone.png"))); // NOI18N
        jPanel1.add(labelicone);
        labelicone.setBounds(30, 40, 40, 40);

        labeltitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labeltitulo.setText("Médico - Adicionar");
        jPanel1.add(labeltitulo);
        labeltitulo.setBounds(80, 50, 310, 20);

        jPanel4.setBackground(new java.awt.Color(204, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel4.setLayout(null);

        jPanel5.setBackground(new java.awt.Color(153, 153, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel5.setLayout(null);

        labelcodigo.setText("Código");
        jPanel5.add(labelcodigo);
        labelcodigo.setBounds(40, 80, 60, 16);

        labelsubtitulo.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        labelsubtitulo.setText("Sistema de agendamento");
        jPanel5.add(labelsubtitulo);
        labelsubtitulo.setBounds(30, 0, 190, 16);

        textcodigo.setEditable(false);
        textcodigo.setBackground(new java.awt.Color(204, 255, 255));
        textcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textcodigoActionPerformed(evt);
            }
        });
        jPanel5.add(textcodigo);
        textcodigo.setBounds(40, 110, 100, 40);

        labeloperadora.setText("Nome da Operadora");
        jPanel5.add(labeloperadora);
        labeloperadora.setBounds(40, 160, 120, 16);

        textoperadora.setBackground(new java.awt.Color(204, 204, 255));
        jPanel5.add(textoperadora);
        textoperadora.setBounds(40, 190, 340, 22);

        labelplano.setText("Tipo do Plano");
        jPanel5.add(labelplano);
        labelplano.setBounds(40, 240, 80, 16);
        jPanel5.add(textplano);
        textplano.setBounds(40, 270, 340, 22);

        buttonsalvar.setBackground(new java.awt.Color(204, 255, 204));
        buttonsalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/salvar.png"))); // NOI18N
        buttonsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonsalvarActionPerformed(evt);
            }
        });
        jPanel5.add(buttonsalvar);
        buttonsalvar.setBounds(670, 320, 90, 70);

        buttoncancelar.setBackground(new java.awt.Color(255, 153, 153));
        buttoncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/cancel.png"))); // NOI18N
        buttoncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttoncancelarActionPerformed(evt);
            }
        });
        jPanel5.add(buttoncancelar);
        buttoncancelar.setBounds(570, 320, 90, 70);

        jPanel4.add(jPanel5);
        jPanel5.setBounds(20, 10, 790, 400);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(0, 90, 830, 430);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 830, 90);

        jPanel6.setBackground(new java.awt.Color(204, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel6.setLayout(null);

        jPanel7.setBackground(new java.awt.Color(153, 153, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel7.setLayout(null);

        labelcrm.setText("CRM:");
        jPanel7.add(labelcrm);
        labelcrm.setBounds(150, 40, 60, 16);

        labelsubtitulo1.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        labelsubtitulo1.setText("Detalhes do(a) médico(a):");
        jPanel7.add(labelsubtitulo1);
        labelsubtitulo1.setBounds(30, 0, 190, 16);

        textcrm.setEditable(false);
        textcrm.setBackground(new java.awt.Color(204, 255, 255));
        textcrm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textcrmActionPerformed(evt);
            }
        });
        jPanel7.add(textcrm);
        textcrm.setBounds(150, 60, 100, 22);

        labeltelefone.setText("Telefone:");
        jPanel7.add(labeltelefone);
        labeltelefone.setBounds(20, 100, 120, 16);

        texttelefone.setBackground(new java.awt.Color(204, 255, 255));
        jPanel7.add(texttelefone);
        texttelefone.setBounds(20, 120, 150, 22);

        labeldata.setText("Data  Nascimento:");
        jPanel7.add(labeldata);
        labeldata.setBounds(550, 100, 120, 16);

        textdata.setBackground(new java.awt.Color(204, 255, 255));
        jPanel7.add(textdata);
        textdata.setBounds(550, 120, 170, 22);

        buttonsalvar1.setBackground(new java.awt.Color(204, 255, 204));
        buttonsalvar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/salvar.png"))); // NOI18N
        buttonsalvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonsalvar1ActionPerformed(evt);
            }
        });
        jPanel7.add(buttonsalvar1);
        buttonsalvar1.setBounds(670, 320, 90, 70);

        buttoncancelar1.setBackground(new java.awt.Color(255, 153, 153));
        buttoncancelar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/cancel.png"))); // NOI18N
        buttoncancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttoncancelar1ActionPerformed(evt);
            }
        });
        jPanel7.add(buttoncancelar1);
        buttoncancelar1.setBounds(570, 320, 90, 70);

        labelespecialidade.setText("Lista de Especialidades:");
        jPanel7.add(labelespecialidade);
        labelespecialidade.setBounds(30, 190, 150, 16);

        labelcodigo3.setText("Código:");
        jPanel7.add(labelcodigo3);
        labelcodigo3.setBounds(20, 40, 60, 16);

        textnomemedico.setEditable(false);
        textnomemedico.setBackground(new java.awt.Color(204, 255, 255));
        textnomemedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textnomemedicoActionPerformed(evt);
            }
        });
        jPanel7.add(textnomemedico);
        textnomemedico.setBounds(270, 60, 410, 22);

        textcodigo3.setEditable(false);
        textcodigo3.setBackground(new java.awt.Color(204, 255, 255));
        textcodigo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textcodigo3ActionPerformed(evt);
            }
        });
        jPanel7.add(textcodigo3);
        textcodigo3.setBounds(20, 60, 100, 22);

        labelemail.setText("E-mail:");
        jPanel7.add(labelemail);
        labelemail.setBounds(190, 100, 60, 16);

        textemail.setBackground(new java.awt.Color(204, 255, 255));
        jPanel7.add(textemail);
        textemail.setBounds(190, 120, 340, 20);

        labelespmedico.setText("Especialidades do médico:");
        jPanel7.add(labelespmedico);
        labelespmedico.setBounds(260, 190, 150, 16);

        labelnomemedico.setText("Nome do(a) médico(a):");
        jPanel7.add(labelnomemedico);
        labelnomemedico.setBounds(270, 40, 150, 16);

        jlistespmedico.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jlistespmedico);

        jPanel7.add(jScrollPane1);
        jScrollPane1.setBounds(270, 220, 130, 160);

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jlistespecialidade.setViewportView(jList2);

        jPanel7.add(jlistespecialidade);
        jlistespecialidade.setBounds(30, 220, 130, 160);

        jbuttondireita.setBackground(new java.awt.Color(102, 0, 204));
        jbuttondireita.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbuttondireita.setForeground(new java.awt.Color(255, 255, 255));
        jbuttondireita.setText(">");
        jPanel7.add(jbuttondireita);
        jbuttondireita.setBounds(180, 240, 60, 50);

        jbuttonesquerda.setBackground(new java.awt.Color(0, 204, 204));
        jbuttonesquerda.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbuttonesquerda.setForeground(new java.awt.Color(255, 255, 255));
        jbuttonesquerda.setText("<");
        jPanel7.add(jbuttonesquerda);
        jbuttonesquerda.setBounds(180, 310, 60, 50);

        jPanel6.add(jPanel7);
        jPanel7.setBounds(20, 10, 790, 400);

        getContentPane().add(jPanel6);
        jPanel6.setBounds(0, 90, 830, 430);

        setBounds(0, 0, 842, 526);
    }// </editor-fold>//GEN-END:initComponents

    private void textcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textcodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textcodigoActionPerformed

    private void buttonsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonsalvarActionPerformed
        TipoOperacao tipoOperacao = null;
        //Criar um objeto Plano de Saúde

        if (tipoOperacao == TipoOperacao.ADICIONAR) {
            gravar();
        } else {
            atualizar();
        }
    }//GEN-LAST:event_buttonsalvarActionPerformed

    private void buttoncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttoncancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttoncancelarActionPerformed

    private void textcrmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textcrmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textcrmActionPerformed

    private void buttonsalvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonsalvar1ActionPerformed
        TipoOperacao tipoOperacao = null;
        //Criar um objeto Plano de Saúde

        if (tipoOperacao == TipoOperacao.ADICIONAR) {
            gravar();
        } else {
            atualizar();
        }
    }//GEN-LAST:event_buttonsalvar1ActionPerformed

    private void buttoncancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttoncancelar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttoncancelar1ActionPerformed

    private void textnomemedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textnomemedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textnomemedicoActionPerformed

    private void textcodigo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textcodigo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textcodigo3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MedicoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MedicoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MedicoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MedicoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MedicoDialog().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttoncancelar;
    private javax.swing.JButton buttoncancelar1;
    private javax.swing.JButton buttonsalvar;
    private javax.swing.JButton buttonsalvar1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbuttondireita;
    private javax.swing.JButton jbuttonesquerda;
    private javax.swing.JScrollPane jlistespecialidade;
    private javax.swing.JList<String> jlistespmedico;
    private javax.swing.JLabel labelcodigo;
    private javax.swing.JLabel labelcodigo3;
    private javax.swing.JLabel labelcrm;
    private javax.swing.JLabel labeldata;
    private javax.swing.JLabel labelemail;
    private javax.swing.JLabel labelespecialidade;
    private javax.swing.JLabel labelespmedico;
    private javax.swing.JLabel labelicone;
    private javax.swing.JLabel labelmedico;
    private javax.swing.JLabel labelnomemedico;
    private javax.swing.JLabel labeloperadora;
    private javax.swing.JLabel labelplano;
    private javax.swing.JLabel labelsubtitulo;
    private javax.swing.JLabel labelsubtitulo1;
    private javax.swing.JLabel labeltelefone;
    private javax.swing.JLabel labeltitulo;
    private javax.swing.JTextField textcodigo;
    private javax.swing.JTextField textcodigo3;
    private javax.swing.JTextField textcrm;
    private javax.swing.JTextField textdata;
    private javax.swing.JTextField textemail;
    private javax.swing.JTextField textnomemedico;
    private javax.swing.JTextField textoperadora;
    private javax.swing.JTextField textplano;
    private javax.swing.JTextField texttelefone;
    // End of variables declaration//GEN-END:variables

    private void gravar() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void atualizar() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
